config/routes.rb
Rails.application.routes.draw do
  resources :bookings, only: [:new, :create, :show]
  resources :flights, only: [:index]
  root "flights#index"
end

app/models/airport.rb
class Airport < ApplicationRecord
  has_many :departing_flights, foreign_key: 'from_airport_id', class_name: 'Flight'
  has_many :arriving_flights, foreign_key: 'to_airport_id', class_name: 'Flight'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :flight
  has_many :passengers, dependent: :destroy
  accepts_nested_attributes_for :passengers
end

app/models/flight.rb
class Flight < ApplicationRecord
  belongs_to :to_airport, class_name: 'Airport', foreign_key: 'to_airport_id'
  belongs_to :from_airport, class_name: 'Airport', foreign_key: 'from_airport_id'
  has_many :bookings, dependent: :destroy
  has_many :passengers, through: :bookings
end

app/models/passenger.rb
class Passenger < ApplicationRecord
  belongs_to :booking
end

app/controllers/airports_controller.rb
class AirportsController < ApplicationController
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: [:show, :edit, :update, :destroy]

  # GET /bookings/1
  # GET /bookings/1.json
  def show
  end

  # GET /bookings/new
  def new
    @booking = Booking.new(booking_params)
    @booking.num_of_passengers.times { @booking.passengers.build }
  end

  # POST /bookings
  # POST /bookings.json
  def create
    @booking = Booking.new(booking_params)

    respond_to do |format|
      if @booking.save
        send_thanks_emails
        format.html { redirect_to booking_path(@booking), notice: 'Booking was successfully created.' }
        format.json { render :show, status: :created, location: @booking }
      else
        format.html { render :new }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_booking
      @booking = Booking.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def booking_params
      params.require(:booking).permit(:flight_id, :num_of_passengers, passengers_attributes: [:name, :email])
    end

    def send_thanks_emails
      @booking.passengers.each do |passenger|
        PassengerMailer.with(passenger: passenger).thank_you_email.deliver_now!
      end
    end
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  include FlightsHelper

  before_action :set_flight, only: [:show, :edit, :update, :destroy]
  before_action :set_date_options, only: :index
  before_action :set_airport_options, only: :index

  # GET /flights
  # GET /flights.json
  def index
    if search?
      if params[:from_airport_id].empty? && !params[:to_airport_id].empty?

        @flights = Flight.where(to_airport_id: params[:to_airport_id],
                                date: params[:date])

      elsif !params[:from_airport_id].empty? && params[:to_airport_id].empty?

        @flights = Flight.where(from_airport_id: params[:from_airport_id],
                                date: params[:date])
      
      elsif !params[:from_airport_id].empty? && !params[:to_airport_id].empty?

        @flights = Flight.where(to_airport_id: params[:to_airport_id],
                                from_airport_id: params[:from_airport_id],
                                date: params[:date])

      else
        @flights = Flight.where(date: params[:date])
      end
      @booking = Booking.new
    else
      @flights = Flight.all
    end
  end
end

app/controllers/passengers_controller.rb
class PassengersController < ApplicationController
  before_action :set_passenger, only: [:show, :edit, :update, :destroy]

  # GET /passengers
  # GET /passengers.json
  def index
    @passengers = Passenger.all
  end

  # GET /passengers/1
  # GET /passengers/1.json
  def show
  end

  # GET /passengers/new
  def new
    @passenger = Passenger.new
  end

  # GET /passengers/1/edit
  def edit
  end

  # POST /passengers
  # POST /passengers.json
  def create
    @passenger = Passenger.new(passenger_params)

    respond_to do |format|
      if @passenger.save
        format.html { redirect_to @passenger, notice: 'Passenger was successfully created.' }
        format.json { render :show, status: :created, location: @passenger }
      else
        format.html { render :new }
        format.json { render json: @passenger.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /passengers/1
  # PATCH/PUT /passengers/1.json
  def update
    respond_to do |format|
      if @passenger.update(passenger_params)
        format.html { redirect_to @passenger, notice: 'Passenger was successfully updated.' }
        format.json { render :show, status: :ok, location: @passenger }
      else
        format.html { render :edit }
        format.json { render json: @passenger.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /passengers/1
  # DELETE /passengers/1.json
  def destroy
    @passenger.destroy
    respond_to do |format|
      format.html { redirect_to passengers_url, notice: 'Passenger was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_passenger
      @passenger = Passenger.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def passenger_params
      params.require(:passenger).permit(:name, :email)
    end
end

app/helpers/airports_helper.rb
module AirportsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/flights_helper.rb
module FlightsHelper

  private
    
  def set_flight
    @flight = Flight.find(params[:id])
  end

  def flight_params
    params.require(:flight).permit(:to_airport_id,
                                   :from_airport_id,
                                   :date,
                                   :time,
                                   :duration)
  end

  def set_airport_options
    @airport_options = Airport.all.map { |a| [a.code, a.id] }
  end

  def set_date_options
    @date_options = Flight.all.map { |f| [f.date.strftime('%b %d, %Y'), f.date]}.uniq
  end

  def format_date
    Date.civil(params[:year].to_i, params[:month].to_i, params[:day].to_i)
  end

  def search?
    params.has_key?(:num_of_passengers) && 
    params.has_key?(:date)
  end

end

app/helpers/passengers_helper.rb
module PassengersHelper
end

app/views/bookings/_form.html.erb
<%= simple_form_for(@booking, local: true) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
  
  <% i = 1 %>
    <%= f.simple_fields_for :passengers do |p|%>
      <p class="title is-5">Passenger <%= i %></p>
      <div class="field">
        <div class="control has-icons-left">
          <%= p.input_field :name,
                             class: "input is-info is-small",
                             label: false,
                             placeholder: 'Name' %>
          <span class="icon is-left">
            <i class="fa fa-signature"></i>
          </span>
        </div>
      </div>
      <div class="field">
        <div class="control has-icons-left">
          <%= p.input_field :email,
                      class: "input is-info is-small",
                      label: false,
                      placeholder: 'Email Address' %>
          <span class="icon is-left">
            <i class="fa fa-at"></i>
          </span>
        </div>
      </div>
      <% i += 1 %>
    <% end %>
    <div class="field is-hidden">
      <div class="control">
        <%= f.input :flight_id, as: :hidden, value: params[:flight_id] %>
      </div>
    </div>
    <div class="field is-hidden">
      <div class="control">
        <%= f.input :num_of_passengers, as: :hidden, value: params[:num_of_passengers] %>
      </div>
    </div>
    <br>
  <div class="form-actions">
    <%= f.button :submit, class: "button is-info" %>
  </div>
<% end %>

app/views/bookings/new.html.erb
<section class="section">
  <div class="container">
    <div class="columns">
      <div class="box column is-half is-offset-one-quarter has-text-centered">
        <nav class="level">
          <div class="level-item has-text-centered">
              <div>
                <p class="heading">From</p>
                <p class="title is-7"><%= @booking.flight.from_airport.code %></p>
              </div>
          </div>
          <div class="level-item has-text-centered">
            <div>
              <p class="heading">To</p>
              <p class="title is-7"><%= @booking.flight.to_airport.code %></p>
            </div>
          </div>
          <div class="level-item has-text-centered">
            <div>
              <p class="heading">Date</p>
              <p class="title is-7"><%= @booking.flight.date %></p>
            </div>
          </div>
          <div class="level-item has-text-centered">
            <div>
              <p class="heading">Flight ID</p>
              <p class="title is-7"><%= @booking.flight_id %></p>
            </div>
          </div>
        </nav>
        <div class="columns is-centered">
          <div class="column is-7">
            <%= render 'form', booking: @booking %>
          </div>
        </div>
      </div>
    </div>
  </div>
  <br>
</section>

app/views/bookings/show.html.erb
<section class="section">
  <div class="container">
    <div class="columns">
      <div class="column is-half is-offset-one-quarter has-text-centered">
        <h1 class="title is-5">Booking for <%= @booking.passengers.first.name.capitalize %></h1>
        <div class="box">
          <nav class="level">
            <div class="level-item has-text-centered">
                <div>
                  <p class="heading">From</p>
                  <p class="title is-7"><%= @booking.flight.from_airport.code %></p>
                </div>
            </div>
            <div class="level-item has-text-centered">
              <div>
                <p class="heading">To</p>
                <p class="title is-7"><%= @booking.flight.to_airport.code %></p>
              </div>
            </div>
            <div class="level-item has-text-centered">
              <div>
                <p class="heading">Date</p>
                <p class="title is-7"><%= @booking.flight.date %></p>
              </div>
            </div>
            <div class="level-item has-text-centered">
              <div>
                <p class="heading">Flight ID</p>
                <p class="title is-7"><%= @booking.flight_id %></p>
              </div>
            </div>
          </nav>
          <div class="columns is-centered">
            <div class="column is-7">
              <p class="title is-5"><%= pluralize(@booking.num_of_passengers, 'Passenger') %></p>
              <% @booking.passengers.each do |passenger| %>
                <p class="subtitle is-5"><%= passenger.name.capitalize %></p>
              <% end %>
            </div>
          </div>
        </div>
        <%= link_to "Back to Flights", root_path, class: "button is-info" %>
      </div>
    </div>
  </div>
  <br>
</section>

app/views/flights/_search.html.erb
<%= form_with(url: flights_path, method: :get, local: true) do |f| %>
  <div class="field">
    <div class="control">
      <div class="select is-primary is-small is-full-width">
        <%= select_tag(:from_airport_id, options_for_select(@airport_options,
                                                            selected: params[:from_airport_id]),
                                                            include_blank: 'From') %>
      </div>
    </div>
  </div>
  <div class="field">
    <div class="control">
      <div class="select is-primary is-small">
        <%= select_tag(:to_airport_id, options_for_select(@airport_options,
                                                          selected: params[:to_airport_id]),
                                                          include_blank: 'To') %>
      </div>
    </div>
  </div>
  <div class="field">
    <div class="control">
      <div class="select is-primary is-small">
        <%= select_tag(:num_of_passengers,
                      options_for_select([["1 Passenger", 1], ["2 Passengers", 2], ["3 Passengers", 3], ["4 Passengers", 4]],
                                          selected: params[:num_of_passengers])) %>
      </div>
    </div>
  </div>
  <div class="field">
    <div class="control">
      <div class="select is-primary is-small">
        <%= select_tag(:date,
                      options_for_select(@date_options, selected: params[:date])) %>
      </div>
    </div>
  </div>
  <div class="field">
    <div class="control">
      <%= f.button :submit %>
    </div>
  </div>
<% end %>

<!--



-->

app/views/flights/_search_results.html.erb
<%= simple_form_for @booking, url: new_booking_path, method: :get, local: true do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>


  <div class="columns">
    <div class="column">
      <% @flights.each do |flight| %>
        <div class="field">
          <div class="control">
            <nav class="level box">
              <% if flight == @flights.first %>
                <%= f.radio_button :flight_id, flight.id, checked: true %>
              <% else %>
                <%= f.radio_button :flight_id, flight.id %>
              <% end %>
              <div class="level-item has-text-centered">
                <div>
                  <p class="heading">From</p>
                  <p class="title is-7"><%= flight.from_airport.code %></p>
                </div>
              </div>
              <div class="level-item has-text-centered">
                <div>
                  <p class="heading">To</p>
                  <p class="title is-7"><%= flight.to_airport.code %></p>
                </div>
              </div>
              <div class="level-item has-text-centered">
                <div>
                  <p class="heading">Date</p>
                  <p class="title is-7"><%= flight.date.strftime('%B %-d, %Y') %></p>
                </div>
              </div>
              <div class="level-item has-text-centered">
                <div>
                  <p class="heading">Time</p>
                  <p class="title is-7"><%= flight.time.strftime('%l:%M %p') %></p>
                </div>
              </div>
            </nav>
          </div>
        </div>
      <% end %>
    </div>
    <div class="field is-hidden">
      <div class="control">
        <%= f.radio_button :num_of_passengers, params[:num_of_passengers], checked: true %>
      </div>
    </div>
    <div class="column is-3">
      <div class="field" id="fixed-button">
        <div class="control">
          <%= f.button :submit, class: "button is-link" %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/flights/index.html.erb
<section class="section">
  <div class="container">
    <div class="columns">
      <div class="column is-3 has-text-centered">
        <div class="box">
          <p class="title is-5">Search</p>
          <%= render 'search' %>
        </div>
      </div>
      <div class="column has-text-centered">
        <% if search? %>
          <%= render 'search_results' %>
        <% else %>
          <% @flights.sample(10).each do |flight| %>
            <nav class="level box">
              <div class="level-item has-text-centered">
                <div>
                  <p class="heading">From</p>
                  <p class="title is-7"><%= flight.from_airport.code %></p>
                </div>
              </div>
              <div class="level-item has-text-centered">
                <div>
                  <p class="heading">To</p>
                  <p class="title is-7"><%= flight.to_airport.code %></p>
                </div>
              </div>
              <div class="level-item has-text-centered">
                <div>
                  <p class="heading">Date</p>
                  <p class="title is-7"><%= flight.date.strftime('%B %-d, %Y') %></p>
                </div>
              </div>
              <div class="level-item has-text-centered">
                <div>
                  <p class="heading">Time</p>
                  <p class="title is-7"><%= flight.time.strftime('%l:%M %p') %></p>
                </div>
              </div>
            </nav>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Odin Flight Booker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.9.0/css/all.min.css">
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="has-background-info">
      <nav class="level" id="navbar">
        <div class="level-item has-text-centered">
          <%= link_to "Odin Flight Booker", root_path, class: "title has-text-white" %>
        </div>
      </nav>
    </div>
    
    <% if flash[:notice] %>
      <div class="notification is-primary global-notification has-text-centered">
        <p class="notice"><%= notice %></p>
      </div>
    <% end %>
    <% if flash[:alert] %>
      <div class="notification is-danger is-light global-notification has-text-centered">
        <p class="alert"><%= alert %></p>
      </div>
    <% end %>

    <%= yield %>
  </body>
</html>